version: '3.9'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: bets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  line-provider:
    build: ./line-provider
    ports:
      - "8000:8000"

  bet-maker:
    build: ./bet-maker
    env_file:
      - .env
    depends_on:
      - db
      - line-provider
    ports:
      - "8001:8001"

volumes:
  pgdata:
